### ISSUE TITLE
Ordered Container: full hierarchy

### ISSUE THREAD

**Issue by olance** [jotomo/neo4j-gist-challenge#1]
Hi @jotomo :)

thanks a lot for your ordered container gist, being a beginner in Neo4J/graph DB I have spent hours trying to model ordered hierarchies and had settled for a model with index on relationships. Your Dr. Who example is kind of an eye-opener for me! ^^

I have one question though: you haven't included any Cypher queries with your last example, and I'd like to know if there's any way to get the full Dr. Who hierarchy, with items in correct order, with a single query?

The ideal output would be something like:

Item | Depth
-------|-------
Dr. Who|0
Season 1|1
S01E01|2
S01E02|2
Season 2|1
S02E01|2
S02E02|2

I guess the `Depth` column wouldn't be mandatory as it could be inferred from each item's label, but I guess you've got the idea... So is it possible?  
As there are three types of relationships to follow (:FIRST, :NEXT and :VALUE) and to a possibly unknown maximum depth (that would be my own requirement), I'm not sure it's achievable...

Thanks for your insight!

**Comment by jotomo** [comment]
Glad to hear it's helpful! :-)
I kind ran out of steam/time before adding Cypher queries. A single query should be possible to get seasons and episodes, a generic query that goes deeper might be tricker, but _should_ be possible ...
I'll give this a go on the weekend.

**Comment by olance** [comment]
hey thanks for replying so quickly! :)

Asking you actually got me thinking a bit differently, and I came to a solution that's gonna be reasonable for me to begin with!

I just realized your items and relationships to the tree were just the graph version of a breadth-first search (or kind of ^^), so I figured I could just use a depth-first search instead!

Here's what I've come up with:
![](https://photos-3.dropbox.com/t/2/AABLTAsBEYtjKjj7H1d8Hm4TobTnJ5qc8orpX30VlptiGg/12/19555479/png/32x32/1/1432908000/0/2/Capture%20d'%C3%A9cran%202015-05-29%2014.12.52.png/CJfJqQkgASgB/z6rTChyQmwxwLNh5qwRQdKgjYogKH4r0nQeRGUD2Bxo?size=1024x768&size_mode=2)

With the items (red dots) pointing to each tree node in depth-first traversal order, there's no need for recursion anymore and a single query can return the whole tree as I need it:

```
MATCH (root:Series)-[:FIRST]->(first:Item)-[:NEXT*0..]->(:Item)-[:VALUE]->(item)
WITH root + collect(item) AS nodes UNWIND nodes AS items
RETURN DISTINCT items
```

I have created an example in Neo4j's console here: http://console.neo4j.org/r/sh5x9i

Of course the does not allow querying a single tree level, but in my case that's really not what I needed.

What do you think?

**Comment by olance** [comment]
I think this model could actually be complete with `FIRST` and `LAST` relationships from each non-leaf node to the correct `Item` nodes and then that would give a "generic" solution to have the full ordered hierarchy *or* any level's subtree (ordered too) with a single query.

Add a `depth` property to each `Item` node (or each `VALUE` relationship?) and you could also query the direct children of any tree node.

I think I will investigate ^_^

**Comment by jotomo** [comment]
Cool. I've been playing around a bit, this one is more generic and should work for all levels:
```
MATCH (root:Series)-[:FIRST|NEXT*0..]->(:Item)-[:VALUE]->(item)
WITH root + collect(item) AS nodes UNWIND nodes AS items
RETURN items
```

Btw. displaying paths is a nice way to see how Cypher traverses the graph:
```
MATCH p=(root:Series)-[:FIRST|NEXT*0..]->(:Item)-[:VALUE]->(item)
RETURN p
```

```
[(0:Series {title:"Dr Who"}), (0)-[2:FIRST]->(7), (7:Item), (7)-[7:VALUE]->(1), (1:Season {title:"Season 1"})]
[(0:Series {title:"Dr Who"}), (0)-[2:FIRST]->(7), (7:Item), (7)-[8:NEXT]->(8), (8:Item), (8)-[9:VALUE]->(2), (2:Episode {title:"S01E01"})]
[(0:Series {title:"Dr Who"}), (0)-[2:FIRST]->(7), (7:Item), (7)-[8:NEXT]->(8), (8:Item), (8)-[10:NEXT]->(9), (9:Item), (9)-[11:VALUE]->(3), (3:Episode {title:"S01E02"})]
[(0:Series {title:"Dr Who"}), (0)-[2:FIRST]->(7), (7:Item), (7)-[8:NEXT]->(8), (8:Item), (8)-[10:NEXT]->(9), (9:Item), (9)-[12:NEXT]->(10), (10:Item), (10)-[13:VALUE]->(4), (4:Season {title:"Season 2"})]
[(0:Series {title:"Dr Who"}), (0)-[2:FIRST]->(7), (7:Item), (7)-[8:NEXT]->(8), (8:Item), (8)-[10:NEXT]->(9), (9:Item), (9)-[12:NEXT]->(10), (10:Item), (10)-[14:NEXT]->(11), (11:Item), (11)-[15:VALUE]->(5), (5:Episode {title:"S02E01"})]
[(0:Series {title:"Dr Who"}), (0)-[2:FIRST]->(7), (7:Item), (7)-[8:NEXT]->(8), (8:Item), (8)-[10:NEXT]->(9), (9:Item), (9)-[12:NEXT]->(10), (10:Item), (10)-[14:NEXT]->(11), (11:Item), (11)-[16:NEXT]->(12), (12:Item), (12)-[17:VALUE]->(6), (6:Episode {title:"S02E02"})]
```

I think an explicit depth property isn't needed but can be calculated from Cypher, something like extracting rels from a path and counting them. My mind's a bit slow at the moment though - friday and all ;-)

Let me know what you come up with. And maybe put it up as a GraphGist later? :-)

**Comment by olance** [comment]
Ah, good idea for the depth part!

And you're right about returning paths, that's a nice trick :)
Actually I was thinking that ordering by path length might be necessary? Or are we sure Neo4j will always start by the shortest path and expand one relationship by one relationship?

I was thinking about making a GraphGist yes, that'd be nice ^^

**Comment by jotomo** [comment]
> Actually I was thinking that ordering by path length might be necessary? 
> Or are we sure Neo4j will always start with the shortest path and expand one 
> relationship by one relationship?

I can't find anything in the docs right now. I think I remember Neo4j will return the shortest match right away and then continue, which works here because each element return has a different length (if paths had the same length that would be an issue). However, memory is a fuzzy thing ... 
To be safe: _RETURN ... ORDER BY length(path)_

**Comment by olance** [comment]
yeap all right :)
Thanks again, I'll try to dig a little bit further and submit my own GraphGist :)

**Comment by jotomo** [comment]
Hi @olance , sorry I didn't get around to looking into this further during the weekend. You seem to be getting alone fine though, and probably know more than I about querying this case by now, since I'm working in embedded mode, directly accessing the graph most of the time (instead of using cypher).

**Comment by olance** [comment]
Hey, no worries!
You set me on the right path (ahah) and that's great already :)
